apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-demo-configmap
data:
  pghost: {{ .Values.postgresql.service.clusterIP | quote }}
  pgport: "5432"
  pguser: postgres
  pgpwd: postgres12
  GOPATH: "/root/work/"
