apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-demo-deployment
  labels:
    app: helm-demo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helm-demo-pod
  template:
    metadata:
      labels:
        app: helm-demo-pod
    annotations:
      # The field we'll use to couple our ConfigMap and Deployment
      configHash: ""
    spec:
      containers:
      - name: helmdemogo
        image: helm_demo_go:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
            name: helm-demo-configmap