apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-demo-deployment
  labels:
    app: helm-demo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helm-demo-pod
  template:
    metadata:
      labels:
        app: helm-demo-pod
      annotations:
        configHash: 2aaa726da1dad8655fe42cbb53ef593d
    spec:
      containers:
      - name: helmdemogo
        image: helm_demo_go:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef: 
            name: helm-demo-configmap
